export const data = {
  highlights: [
    { number: 1, tactic: 'Write It Down' },
    { number: 2, tactic: 'Groundhog It (or, "Do Yesterday Again")' },
    { number: 3, tactic: 'Stack Rank Your Life' },
    { number: 4, tactic: 'Batch the Little Stuff' },
    { number: 5, tactic: 'The Might-Do List' },
    { number: 6, tactic: 'The Burner List' },
    { number: 7, tactic: 'Run a Personal Sprint' },
    { number: 8, tactic: 'Schedule Your Highlight' },
    { number: 9, tactic: 'Block Your Calendar' },
    { number: 10, tactic: 'Bulldoze Your Calendar' },
    { number: 11, tactic: 'Flake It Till You Make It' },
    { number: 12, tactic: 'Just Say No' },
    { number: 13, tactic: 'Design Your Day' },
    { number: 14, tactic: 'Become a Morning Person' },
    { number: 15, tactic: 'Nighttime Is Highlight Time' },
    { number: 16, tactic: 'Quit When You\'re Done' },
  ],
  lasers: [
    { number: 17, tactic: 'Try a Distraction-Free Phone' },
    { number: 18, tactic: 'Log Out' },
    { number: 19, tactic: 'Nix Notifications' },
    { number: 20, tactic: 'Clear Your Homescreen' },
    { number: 21, tactic: 'Wear a Wristwatch' },
    { number: 22, tactic: 'Leave Devices Behind' },
    { number: 23, tactic: 'Skip the Morning Check-In' },
    { number: 24, tactic: 'Block Distraction Kryptonite' },
    { number: 25, tactic: 'Ignore the News' },
    { number: 26, tactic: 'Put Your Toys Away' },
    { number: 27, tactic: 'Fly Without Wi-Fi' },
    { number: 28, tactic: 'Put a Timer on the Internet' },
    { number: 29, tactic: 'Cancel the Internet' },
    { number: 30, tactic: 'Watch Out for Time Craters' },
    { number: 31, tactic: 'Trade Fake Wins for Real Wins' },
    { number: 32, tactic: 'Turn Distractions into Tools' },
    { number: 33, tactic: 'Become a Fair-Weather Fan' },
    { number: 34, tactic: 'Deal with Email at the End of the Day' },
    { number: 35, tactic: 'Schedule Email Time' },
    { number: 36, tactic: 'Empty Your Inbox Once a Week' },
    { number: 37, tactic: 'Pretend Messages Are Letters' },
    { number: 38, tactic: 'Be Slow to Respond' },
    { number: 39, tactic: 'Reset Expectations' },
    { number: 40, tactic: 'Set Up Send-Only Email' },
    { number: 41, tactic: 'Vacation Off the Grid' },
    { number: 42, tactic: 'Lock Yourself Out' },
    { number: 43, tactic: 'Don\'t Watch the News' },
    { number: 44, tactic: 'Put Your TV in the Corner' },
    { number: 45, tactic: 'Ditch Your TV for a Projector' },
    { number: 46, tactic: 'Go a la Carte Instead of All-You-Can-Eat' },
    { number: 47, tactic: 'If You Love Something, Set It Free' },
    { number: 48, tactic: 'Shut the Door' },
    { number: 49, tactic: 'Invent a Deadline' },
    { number: 50, tactic: 'Explode Your Highlight' },
    { number: 51, tactic: 'Play a Laser Sound Track' },
    { number: 52, tactic: 'Set a Visible Timer' },
    { number: 53, tactic: 'Avoid the Lure of Fancy Tools' },
    { number: 54, tactic: 'Start on Paper' },
    { number: 55, tactic: 'Make a "Random Question" List' },
    { number: 56, tactic: 'Notice One Breath' },
    { number: 57, tactic: 'Be Bored' },
    { number: 58, tactic: 'Be Stuck' },
    { number: 59, tactic: 'Take a Day Off' },
    { number: 60, tactic: 'Go All In' },
  ],
  energizes: [
    { number: 61, tactic: 'Exercise Every Day (but Don\'t Be a Hero)' },
    { number: 62, tactic: 'Pount the Pavement' },
    { number: 63, tactic: 'Inconvenience Yourself' },
    { number: 64, tactic: 'Squeeze in a Super Short Workout' },
    { number: 65, tactic: 'Eat Like a Hunter-Gatherer' },
    { number: 66, tactic: 'Central Park Your Plate' },
    { number: 67, tactic: 'Stay Hungry' },
    { number: 68, tactic: 'Snack Like a Toddler' },
    { number: 69, tactic: 'Go on the Dark Chocolate Plan' },
    { number: 70, tactic: 'Wake Up Before You Caffeinate' },
    { number: 71, tactic: 'Caffeinate Before You Crash' },
    { number: 72, tactic: 'Take a Caffeine Nap' },
    { number: 73, tactic: 'Maintain Altitude with Green Tea' },
    { number: 74, tactic: 'Turbo Your Highlight' },
    { number: 75, tactic: 'Learn Your Last Call' },
    { number: 76, tactic: 'Disconnect Sugar' },
    { number: 77, tactic: 'Get Woodsy' },
    { number: 78, tactic: 'Trick Yourself into Meditating' },
    { number: 79, tactic: 'Leave Your Headphones at Home' },
    { number: 80, tactic: 'Take Real Breaks' },
    { number: 81, tactic: 'Spend Time with Your Tribe' },
    { number: 82, tactic: 'Eat Without Screens' },
    { number: 83, tactic: 'Make Your Bedroom a Bed Room' },
    { number: 84, tactic: 'Fake the Sunset' },
    { number: 85, tactic: 'Sneak a Nap' },
    { number: 86, tactic: 'Don\'t Jet-Lag Yourself' },
    { number: 87, tactic: 'Put On Your Own Oxygen Mask First' },
  ],
}
